config/routes.rb
Play::Application.routes.draw do
  resources :project_configurations

  get "build/index"
  post "build/clone"
  devise_for :users
  get "stuxnet/deploy"
  get "index" => "build#index"
  get "welcome" => 'static#welcome'
  root 'static#welcome'

end

app/models/destination.rb
class Destination
	def self.exists?
		@configuration = ProjectConfiguration.first
		File.directory?(@configuration.destination)
	end
end

app/models/git.rb
class Git
  def status(target)
    system "cd #{target} && git status"
  end

  def pull(target)
    system "cd #{target} && git pull"
  end

  def remote_v(from)
    %x(cd #{from} && git ls-remote https://github.com/etuchscherer/Play.git | head -1 | awk '{print \$1}')
  end

  def local_v(from)
    %x(cd #{from} && git log | head -1 | awk '{print $2}')
  end
end

app/models/github.rb
module Github
  include RestClient

  def self.new_synchronizer(args = {})
    Sync.new(args)
  end

  class Commits

    def initialize(args = {})
      init_null_object args
    end

    def last_commit
      @commits.first || fail('No commits found')
    end

    def last_commit_sha
      last_commit.fetch('sha').chomp
    end

    def fetch
      @commits = JSON.parse(RestClient.get url_for_commits)
      self
    end

    private

    def init_null_object(args)
      @owner = args[:owner] || '' 
      @name = args[:name] || '' 
      @destination = args[:destination] || '' 
      @source = args[:source] || '' 
    end

    def url_for_commits
      "https://api.github.com/repos/#{@owner}/#{@name}/commits"
    end
  end

  class Sync
    def initialize(args = {})
      init_null_object args
    end

    def master_latest_sha
      remote = Github::Commits.new(owner: @owner, name: @name).fetch.last_commit_sha
    end

    def local_latest_sha
      %x(cd #{@destination} && git rev-parse HEAD).chomp
    end

    def pull
      system "cd #{@destination} && git pull"
    end

    def clone
      system "git clone #{@source} #{@destination}"
    end

    def updated?
      remote = Github::Commits.new(owner: @owner, name: @name)
      remote.fetch.last_commit_sha == local_latest_sha
    end

    private

    def init_null_object(args)
      @owner = args[:owner] ||  ''
      @name = args[:name] ||  ''
      @destination = args[:destination] ||  ''
      @source = args[:source] ||  ''
    end
  end
end

app/models/project_configuration.rb
class ProjectConfiguration < ActiveRecord::Base
	def self.configured?
		ProjectConfiguration.any?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    index_path
  end

  def after_sign_out_path_for(resource)
    welcome_path
  end
end

app/controllers/build_controller.rb
class BuildController < ApplicationController

  before_action :get_config

  def index
  	redirect_to project_configurations_path unless ProjectConfiguration.configured?
    synchronizer
  end

  def clone
  	synchronizer
  	if @sync.clone
  		flash[:notice] = 'Successfully cloned'
  	else
  		flash[:error] = 'Cloning failed'
  	end
  		redirect_to build_index_path
  end

  private

  def synchronizer
    @sync = Github.new_synchronizer({
      owner: @config.owner,
      name: @config.name,
      destination: @config.destination,
      source: @config.source
    }) unless @config.nil?
  end

  def get_config
    @config = ProjectConfiguration.first
  end
end

app/controllers/project_configurations_controller.rb
class ProjectConfigurationsController < ApplicationController
  before_action :set_project_configuration, only: [:show, :edit, :update, :destroy]

  # GET /project_configurations
  # GET /project_configurations.json
  def index
    @configuration = ProjectConfiguration.first
  end

  # GET /project_configurations/new
  def new
    @project_configuration = ProjectConfiguration.new
  end

  # GET /project_configurations/1/edit
  def edit
  end

  # POST /project_configurations
  # POST /project_configurations.json
  def create
    @project_configuration = ProjectConfiguration.new(project_configuration_params)

    respond_to do |format|
      if @project_configuration.save
        format.html { redirect_to project_configurations_path, notice: 'Project configuration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project_configuration }
      else
        format.html { render action: 'new' }
        format.json { render json: @project_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_configurations/1
  # PATCH/PUT /project_configurations/1.json
  def update
    respond_to do |format|
      if @project_configuration.update(project_configuration_params)
        format.html { redirect_to project_configurations_path, notice: 'Project configuration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_configurations/1
  # DELETE /project_configurations/1.json
  def destroy
    @project_configuration.destroy
    respond_to do |format|
      format.html { redirect_to project_configurations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_configuration
      @project_configuration = ProjectConfiguration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_configuration_params
      params.require(:project_configuration).permit(:name, :owner, :source, :destination, :enabled)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def welcome
  	redirect_to build_index_path if user_signed_in?
  end

  def index
    redirect_to welcome_path unless user_signed_in?
    redirect_to configurations_path unless ProjectConfiguration.configured?
    @git = Git.new
  end
end

app/controllers/stuxnet_controller.rb
class StuxnetController < ApplicationController

	before_action :synchronizer

	def deploy
		if @sync.pull
			redirect_to '/'
		else
			fail
		end
	end

	private

	def synchronizer
		@config = ProjectConfiguration.first
		@sync = Github.new_synchronizer({
			owner: @config.owner,
			name: @config.name,
			destination: @config.destination,
			source: @config.source
		}) unless @config.nil?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sign_in_sign_out_button
    if user_signed_in?
      link_to 'Sign Out', destroy_user_session_path, method: :delete
    else
      link_to 'Sign In', new_user_session_path
    end
  end

  def settings_button
    if ProjectConfiguration.configured? && user_signed_in?
      link_to 'Settings', project_configurations_path
    end
  end

  def configured_project_is_current
    config = ProjectConfiguration.first
    Github.new_synchronizer({
      owner: config.owner,
      name: config.name,
      destination: config.destination,
      source: config.source  
    }).updated?
  end
end

app/helpers/build_helper.rb
module BuildHelper
end

app/helpers/project_configurations_helper.rb
module ProjectConfigurationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/stuxnet_helper.rb
module StuxnetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Play</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/alerts' %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/project_configurations/_form.html.erb
<%= form_for(@project_configuration, html: {class: 'form-horizontal'}) do |f| %>
  <% if @project_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_configuration.errors.count, "error") %> prohibited this project_configuration from being saved:</h2>

      <ul>
      <% @project_configuration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'col-sm-10 form-control', placeholder: 'My_Awesome_App' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :owner, class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= f.text_field :owner, class: 'col-sm-10 form-control', placeholder: 'Github_User_Name' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :source, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :source, class: 'col-sm-10 form-control', placeholder: 'https://github.com/me/my_awesome_app.git' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :destination, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :destination, class: 'col-sm-10 form-control', placeholder: '/opt/onTrack/project/my_awesome_app' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box :enabled %> Enable Project
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-large btn-success' %>
    </div>
  </div>
<% end %>

app/views/project_configurations/edit.html.erb
<h1>Editing project_configuration</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_configuration %> |
<%= link_to 'Back', project_configurations_path %>

app/views/project_configurations/index.html.erb
<h1>Project Configuration</h1>

<% if !ProjectConfiguration.configured? %>
  <div class="alert alert-warning">This project has not been configured yet!</div>
  <%= link_to 'Create Project Configuration', new_project_configuration_path, class: 'btn btn-success' %>

<% else %>

  <table class="table">
    <thead>
      <tr>
        <th>Repo Name</th>
        <th>Destination (Local)</th>
        <th>Enabled</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @configuration.owner %>/<%=@configuration.name %></td>
          <td><%= @configuration.destination %></td>
          <td><%= @configuration.enabled %></td>
        </tr>
    </tbody>
  </table>

  <br>

  <div class="pull-right">
    <%= link_to 'Edit Project configuration', edit_project_configuration_path(@configuration), class: 'btn btn-warning' %>
    <%= link_to 'Done', build_index_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/project_configurations/new.html.erb
<h1>New Project Configuration</h1>
<br><br>	

<%= render 'form' %>

app/views/shared/_alerts.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Heads up!</strong> <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Warning!</strong> <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">onTrack</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= settings_button %></li>
        <li><%= sign_in_sign_out_button %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/stuxnet/deploy.html.erb
<p>
  working...
</p>